---
title: "Using Classification to Build a Marketing Target Model"
subtitle: "DATA622-Lab3"
embed-resources: true
warning: false
error: false
format:
  html: 
    theme: litera
    code-overflow: wrap
    code-block-bg: true
toc: true
toc-expand: 6
toc-location: right
editor: visual
jupyter: python3
---

::: {.card .border-primary .mb-3 style="padding: 35px"}
In this lab assignment you will be exploring the Portuguese Bank Marketing
Dataset, which consists of data on the outcomes of marketing calls to bank
clients offering them a term deposit. A term deposit is a fixed term deposit
with the bank that returns the principal plus interest at the end of the
pre-defined term period. The objective of this assignment is to apply
classification models to make suggestions to the marketing team.

The dataset can be found at the following link:
[bank_marketing_dataset.csv](https://github.com/georgehagstrom/DATA622Spring2026/blob/main/website/assignments/labs/labData/bank_marketing_dataset.csv).
This dataset is a standard benchmark for classification in the ML community, see
the [UCI Machine Learning Repository
page](https://archive.ics.uci.edu/dataset/222/bank+marketing), and this
introductory paper: [A data driven approach to predict the success of bank
telemarketing](https://repositorio.iscte-iul.pt/bitstream/10071/9499/5/dss_v3.pdf).
The specific dataset used for this assignment has some subtle differences to
those available at the 'UCI Page'. The data is described on the course website
at
[bank_marketing_dictionary](https://georgehagstrom.github.io/DATA622Spring2026/assignments/labs/labData/bank_marketing_dictionary.html)[.qmd](labData/bank_marketing_dictionary.qmd).
:::

--------------------------------------------------------------------------------

```{python}
#-- Package Load--
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report, roc_auc_score, roc_curve
from sklearn.calibration import calibration_curve
```

## The Data:

```{python}
bank=pd.read_csv("https://raw.githubusercontent.com/georgehagstrom/DATA622Spring2026/refs/heads/main/website/assignments/labs/labData/bank_marketing_dataset.csv", header= 0)
bank= bank.drop(columns=["Unnamed: 0"])
bank.head(10)
```

--------------------------------------------------------------------------------

<br>

::: {.card .border-primary .mb-3 style="padding: 35px"}
## Problem 1: What Can Machine Learning Do?

This dataset has been analyzed extensively by many different people. Kaggle.com
is a machine learning community that shares datasets, analysis methods, and
hosts competitions. The most upvoted analysis notebook on kaggle for the Bank
Marketing dataset

(see:
<https://www.kaggle.com/code/janiobachmann/bank-marketing-campaign-opening-a-term-deposit>)
has a glaring flaw that makes it useless in practice. Examine the analysis and
determine the flaw. Your answer should be short.

Hint: Take a careful look at all the variables used, or look for people
complaining about it in the comments.
:::

In the analysis linked, the call duration variable was used to recommend two
strategies, but the call duration is downstream.

The flow:

<div>

$$
call \rightarrow interested\ prospect \rightarrow questions
$$

$$
\\ \rightarrow registration  \rightarrow new client \rightarrow call\ ends \rightarrow call\ duration
$$

</div>

<br>

<center>and</center>

<br>

<div>

$$
call \rightarrow disnterested\ prospect \rightarrow call\ ends \rightarrow call\ duration
$$

</div>

Call duration would hypothetically be longer for the client to subscribes vs one
that does not. However, we don't have a call duration until the call happens.
The model would focus on this variable. This is "data leakage".

--------------------------------------------------------------------------------

## Data Dictionary

::: {.list-group-item .list-group-item-secondary .p-3}
<details>

<summary>

<strong>

<h4>Variable/ Description/ Role</h4>

</strong>

</summary>

**age**: client age in years (feature) (integer)

**job**: occupation type (admin, blue-collar, entrepreneur, housemaid,
management, retired, self-employed, services, student, technician, unemployed,
unknown) (feature) (categorical)

**marital**: marital status (married, divorced, single; divorced includes
widowed) (feature) (categorical)

**education**: education level (primary, secondary, tertiary, unknown) (feature)
(categorical)

**default**: has credit in default (feature) (binary)

**balance**: average yearly balance in euros (feature) (integer)

**housing**: has housing loan (feature) (binary)

**loan**: has personal loan (feature) (binary)

**contact**: contact communication type (cellular, telephone, unknown) (feature)
(categorical)

***month**: last contact month of year (feature) (categorical)**(time
periods)***

***day**: day of call (feature) (integer) **(time periods)***

**duration**: duration of marketing call (feature) (integer)

**campaign**: number of contacts during this campaign for this client (feature)
(integer)

**pdays**: days since last contact from a previous campaign (-1 means not
previously contacted) (feature) (integer)

**previous**: number of contacts before this campaign for this client (feature)
(integer)

**poutcome**: outcome of previous marketing campaign (unknown, failure, other,
success) (feature) (categorical)

***month_numeric**: month of the call (feature) (integer)**(time periods)***

**year**: year of the call (feature) (integer)

***euribor3m**: Euribor 3-month rate — daily indicator (feature) (numeric)
**(time periods)***

***emp.var.rate**: employment variation rate in Portugal — quarterly indicator
(feature) (numeric)- **(time periods)***

***nr.employed**: number of employees in Portugal — quarterly indicator
(thousands) (feature) (numeric) **(time periods)***

***cons.price.idx**: consumer price index in Portugal — monthly indicator
(feature) (numeric) **(time periods)***

***cons.conf.idx**: consumer confidence index in Portugal — monthly indicator
(feature) (numeric) **(time periods)***

**y**: has the client subscribed a term deposit (target) (binary)

</details>
:::

<br>

::: {.card .border-primary .mb-3 style="padding: 35px"}
## Problem 2: EDA and Baseline Model

#### EDA and Temporal Patterns:

Take a quick look at the initial distribution of the data, and perform a
train-test split. **Justify your choice of whether to stratify your split or not
and if so by which variable (consider reading the rest of the question before
deciding).**

Are there any additional variables that need to be added or recoded? Describe
the most important relationships that you uncovered between the predictors and
the target and show the visualizations you made specifically to support those
conclusions.

Pay particular attention to temporal variations in addition to correlation with
the target: how did the success rate of the marketing campaign and the
composition of the target population vary over time? Which variables (and
related real world events) explain the temporal pattern?
:::

There aren't any NA values in the traditional sense, some variables contain
"unknown" or "999" as NA. There are also several variables with high cardinality
that might take over my model as noise. A couple other variables would have been
coded as binary, but because of their "unknown" datapoints, I'll recode in
onehot encoding so "unknown" is its own category, just in case. `pdays` would
probably be more useful in one-hot as well. The time variables will be used to
visualize the clean data but will be removed before the baseline model.

```{python}
#| echo: true
#| eval: false
#| label: NA_Check
#| code-fold: true
#| code-summary: "Code: Examining NA counts and Cardinality"

#--NA and Cardinality count--
pd.DataFrame({"type": bank.dtypes.values, "na_count": bank.isna().sum(),
"type_count": bank.nunique().values}).sort_values("type_count", ascending= False)
```

The dataset is composed of far more "no" than "yes", this imbalance will result
in an unreliable model because of a bias. It may largely predict the majority
class ("No"), rather than help answer the question "What clients are likely to
say 'yes'?". The test split will need to be stratified to handle the "class
imbalance".

```{python}
#| label: target_check
#| code-fold: true
#| code-summary: "Code: Looking at Target" 

sns.set_theme(style="whitegrid", palette= "Dark2", font= "Canva Sans", font_scale= 1.1)

plt.figure()
sns.histplot(data= bank, x= "y")
plt.title("Has Client Subscribed a Term Deposit? ", pad= 25)
plt.xlabel("")
plt.show()

```

The distribution of client **age** is right skewed, suggesting a relationship
might be nonlinear. The peak, where most clients fall are between ages 30-40.
The balance data is also right skewed but in an extreme way. The `balance`
variable will have to be transformed/normalized. The last few plots are
variables whose data points recorded over time periods, but unlike duration,
they're contextual and not leakage.

```{python}
#| label: Preliminary_Visuals
#| code-fold: true
#| code-summary: "Code: Histograms of Continous"

continuous1= bank[["age","balance","emp.var.rate", "nr.employed", "cons.conf.idx", "cons.price.idx", "euribor3m"]]

label_map= {"age": "Age Distribution",
"balance": "Account Balance Distribution",
"emp.var.rate": "Employment Variation Rate",
"nr.employed": "Number of Employees",
"cons.conf.idx": "Consumer Confidence Index",
"cons.price.idx": "Consumer Price Index",
"euribor3m": "Euribor Rate- 3 Months"}

for col in continuous1.columns:
  plt.figure()
  sns.histplot(continuous1[col], kde=False)
  title= label_map[col]
  plt.title(title, pad=15)
  plt.xlabel(col)
  plt.ylabel("Count")
  plt.show()
```

--------------------------------------------------------------------------------

<div>

### Data Clean Overview

-   Binary: `housing`, `loan`, `default`, and `y` will use binary encoding
-   Ordinal: `education` to be mapped by level
-   Nominal: `job`, `marital`, `contact`, `poutcome` will be onehot encoded
-   Discrete: `campaign`, `previous`
-   Special:
    -   `pdays` will be turned into a binary variable denoting if a client was
        ever contacted or not.
    -   time variables will be separated into regular time (`year`, `day`,
        `month_numeric`) and measures over time (`emp.var.rate`, `nr.employed`,
        `cons.conf.idx`, `cons.price.idx`, `euribor3m`)

</div>

--------------------------------------------------------------------------------

```{python}
#| code-fold: true
#| label: Encode-Clean
#| code-summary: "Code: Data Prep and Encoding"


#--Organizing-- 
time=["year", "day", "month_numeric"]
over_time=["emp.var.rate", "nr.employed", "cons.conf.idx", "cons.price.idx", "euribor3m"]

#--pdays modified to if client was contacted before "-1" --
bank["prev_contact"]= (bank["pdays"] !=-1).astype(int)

#--Recoding--
#binary
bank["y"]= bank["y"].map({"yes":1, "no":0})

bank["education"]= bank["education"].map({"unknown": 0, "primary": 1, "secondary": 2, "tertiary": 3})

#--One hot---
onehot= ["job", "marital", "poutcome", "default", "housing", "loan", "contact"]
bank= pd.get_dummies(bank, columns= onehot, drop_first= True, dtype=int)

#-- Dropping-- 
bank= bank.drop(columns=["duration", "pdays"])
```

A bar plot of average monthly subscription to term deposit depicts March,
September, October, and December on average have the highest subscriptions to a
term deposit in the overall time span of the dataset.

```{python}
#| label: Over_time_Visual_Month
#| code-fold: true
#| code-summary: "Code: Barplot of Average Subscription by Month "

#-- Mapping Month--
month_names= {1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun", 7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"}

bank["month_name"]= bank["month_numeric"].map(month_names)

plt.figure()
sns.barplot(x= "month_name", y= "y", data= bank, order= ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], errorbar= None)
plt.title("Average Monthly Subscriptions to a Term Deposit", pad= 25)
plt.ylabel("")
plt.xlabel("")
plt.show()
```

A line plot of our target vs the year variable shows an upward trend in average
subscriptions to a term deposit between 2008 to 2010. The data does not contain
data points for 2007 when the infamous "Global Financial Crisis" began in
December of that year, but we see the average subscription rate is below 0.1 in
2008 and rises sharply after the end of The Great Recession in 2009.[^1]

[^1]: The Great Recession-\
    <https://www.federalreservehistory.org/essays/great-recession-of-200709>

```{python}
#| label: Over_time_Visual_Year

plt.figure()
sns.lineplot(data= bank, x= "year", y= "y", estimator= "mean", marker= "o")
plt.title("Yearly Average Subscriptions to a Term Deposit", fontsize=16, pad= 25)
plt.ylabel("")
plt.xlabel("")
plt.xticks(sorted(bank["year"].unique()))
plt.axvspan(2008, 2009, color= "red", alpha= 0.09, label= "Great Recession")
plt.legend()
plt.show()
```

Although we can't truly select features on just the EDA visualizations, there is
an observable link between term deposits and time. There is variation through
time shown in the visualizations.

```{python}
#| code-fold: true
#| label: Corr_Plot
#| code-summary: "Code: Variable Correlation with Target"

#-- target relationships--
corrs= bank.corr(numeric_only=True)["y"].drop("y").sort_values(ascending=False)


plt.figure(figsize=(10, 8))
sns.barplot(x= corrs.values, y= corrs.index, palette= "coolwarm")
plt.title("Correlation with Target (y)")
plt.xlabel("Correlation")
plt.ylabel("")
plt.axvline(0)
plt.show()
```

In examining the correlations between the variables and the target variable, the
temporal features like `year`, `nr.employed`, `euribor3m`, and `emp.var.rate`
stand out.

--------------------------------------------------------------------------------

::: {.card .border-primary .mb-3 style="padding: 35px"}
#### Baseline Model and Data Drift:

The temporal variation in the dataset necessitates a careful approach to model
evaluation. Explain (in one paragraph) why temporal variation in the data could
cause model performance metrics evaluated on the entire testing split to
mismatch the real-time experiences of the marketing team.

The standard way to approach this is to train and test your model against a
"rolling window" of observations, mimicking how the model would be used and
updated in the real world. I suggest taking a simpler approach (due to dramatic
changes in the amount of data in different time periods): using the variables
identified as causing the temporal patterns in 2(a), divide the data into 3 to 4
epochs (you could use `pd.cut()` on a suitable variable).

Implement this plan by creating a baseline logistic regression model, either
through `statsmodels` or `sklearn` (I recommend building your pre-processing
steps and fitting steps into a pipeline). Select variables based on what you
observed to be important in the EDA, but avoid using temporal predictors
(`month_numeric`, `day`, `year`) or any predictor that could not be used to make
a decision on who to call.
:::

Temporal variables provide context, particularly so, when it comes to financial
data. In this dataset, the time span includes a global recession that inevitably
influenced customer financial decisions worldwide. Events such as these change
the magnitude of influence the predictor(s) have over the target variable. These
differences through time mean that normal test splits cut out a piece of
*different* puzzles. Through a model, these different pieces converge into to a
single picture, that may not capture a *particular* moment in time or the
current/ real-time experience of a marketing team.

In the data, `euribor3m` has a 3 month window and is literally used as a point
of reference for the money market.[^2] The variable is the best candidate for an
epoch in this model, so we'll use it to cut what represents economic low,
medium, and high conditions.

[^2]: EFAMA- On the Use of EURIBOR, Jean-Louis Schirmann
    <https://www.efama.org/sites/default/files/files/3Q2%20EURIBOR%20Jean-Louis%20Schirmann_Final.pdf>

```{python}
#| echo: true
#| eval: true
#| code-fold: true
#| label: Epoch_Split
#| code-summary: "Code: Epochs, Splits, and Modeling"

#--creating epochs--
bank["epochs"]= pd.cut(bank["euribor3m"], bins=3, labels= ["low_e", "mid_e", "high_e"])
epochs= bank["epochs"]

#--test split--
x= bank.drop(columns= ["y", "epochs", "month_name"]+ time)
y= bank["y"]

x_train, x_test, y_train, y_test, epochs_train, epochs_test= train_test_split(x, y, epochs, test_size= 0.3, stratify= y, random_state= 212)

model= LogisticRegression(max_iter=10000)
```

Another characteristic of the data that should be addressed are the differing
scales of the variables in the model. `standard scaler` standardizes by using
the average and standard deviation of the training split, which is then used as
transform on the test split.[^3] The logistic regression model is then fit on
this transformation as a baseline model.

[^3]: ISLP- pg 185: Scikit's Standard Scaler (handling large scale variables
    easily)

###### Scaling

```{python}
#| echo: true
#| eval: true
#| code-fold: true
#| label: Model_Fit
#| code-summary: "Code: Scaling and Fitting the Model"

standardize= StandardScaler()
x_train_scaled= pd.DataFrame(standardize.fit_transform(x_train), columns= x_train.columns, index= x_train.index)

x_test_scaled= pd.DataFrame(standardize.transform(x_test), columns= x_test.columns, index= x_test.index)

model.fit(x_train_scaled, y_train)
```

```{python}
#| echo: true
#| eval: true
#| code-fold: true
#| label: ROC
#| code-summary: "Code: 1st Model Results"
#--Model Report--
y_predictions= model.predict(x_test_scaled)
y_score= model.decision_function(x_test_scaled)
print(classification_report(y_test, y_predictions))

#-- ROC--
y_probabilities= model.predict_proba(x_test_scaled)[:, 1]
print("ROC value:", roc_auc_score(y_test, y_probabilities))
```

The model coefficients show that it can predict a customer not signing up for a
term loan (0) with 91% accuracy and agreeing to sign up for a term loan (1) with
69% accuracy. Even after stratifying, there is a clear bias. Despite the model's
ROC value of 77, its mid tier quality is misleading because its not answering
the question it was created to answer. "Which client will sign up for a term
deposit?" The model must be tuned.

#### Selecting Model Tuning Method:

Feature selection could help tune and strengthen the model. The correlations
examined earlier don't account for overlap, confounding effects, or possible
noisy variables. These might be causing the model to fail at its task. Although
a few variables were dropped at the EDA stage of this report, `RFE` is one
method of feature selection to try. The method prunes by ranking and removing
the weakest contributors to prediction.

###### Recursive Feature Elimination (RFE)

```{python}
#| echo: true
#| eval: true
#| code-fold: true
#| label: RFE_Test_1
#| code-summary: "Feature Elimination Test 1"
#-- Feature Elimination Test1--
model= LogisticRegression(max_iter=10000)

rfe= RFE(estimator=model, n_features_to_select=4)
rfe.fit(x_train_scaled, y_train)

#--Results--
results= x_train.columns[rfe.support_]
print(results)
```

RFE reduced the model predictors to `emp.var.rate`, `cons.price.idx` &
`cons.conf.idx`, three economic period indicators and `poutcome_success` (if
previous campaign led to a yes) `housing_yes` (if client has a mortgage) and
`contact_unknown` (if a client has been contacted previously).

With the reduced results of RFE the model can be refit.

```{python}
#| eval: true
#| code-fold: true
#| label: RFE_Test 1-_Retrain
#| code-summary: "Feature Elimination Test 1- Retrain"

#--Retrain--
x_train_rfe= x_train_scaled[results]
x_test_rfe= x_test_scaled[results]

model= LogisticRegression(max_iter=10000)
model.fit(x_train_rfe, y_train)

y_pred= model.predict(x_test_rfe)
y_prob= model.predict_proba(x_test_rfe)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
```

The results weren't comparable to the model pre-elimination. Its worth testing a
high k just to be sure.

```{python}
#| eval: true
#| code-fold: true
#| label: RFE_Test_2
#| code-summary: "Feature Elimination Test 2"

#-- Feature Elimination 2--
model= LogisticRegression(max_iter=10000)
rfe= RFE(estimator=model, n_features_to_select=16)
rfe.fit(x_train_scaled, y_train)

#--Results--
results= x_train.columns[rfe.support_]
print(results)

#--Refit--
x_train_rfe= x_train_scaled[results]
x_test_rfe= x_test_scaled[results]

model= LogisticRegression(max_iter=10000)
model.fit(x_train_rfe, y_train)

y_pred= model.predict(x_test_rfe)
y_prob= model.predict_proba(x_test_rfe)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
```

It seems RFE does not strengthen the model. There isn't justification for it, so
RFE will not be used for the final model.

##### Epochs

::: {.card .border-primary .mb-3 style="padding: 20px"}
For each testing epoch, report the overall error rate and the overall success
rate of the campaign during that epoch for context and comparison.

For each epoch, plot the ROC curve and the probability calibration curve. What
do you notice about the difference in model performance in different periods?
Test the model on the entire testing set and report how the results compare to
the individual epochs.
:::

\
Earlier the data was divided into three epochs to reflect the low, medium, and
high points of economic conditions.

```{python}
#| eval: true
#| code-fold: true
#| label: Epoch_Error_Rates
#| code-summary: "Epoch Error Rates"

epoch_results= pd.DataFrame({"y_true": y_test, "y_pred": y_predictions, "y_prob": y_probabilities, "epoch": epochs_test})

#-- Checking the groups--
for epoch, group in epoch_results.groupby("epoch"):
  success_rate= group["y_true"].mean()
  error_rate= (group["y_true"] != group["y_pred"]).mean()
  roc_auc= roc_auc_score(group["y_true"], group["y_prob"])
  print(epoch)
  print(f"Error: {error_rate:.3f}")
  print(f"Success: {success_rate:.3f}")
  print(f"ROC AUC: {roc_auc:.3f}")
  print()
```

The results show that the high euribor condition epoch predictions (aka when the
banks have highest interest rates) have the lowest error rate but also the
lowest ROC value and successes. Overall it looks like the ROC value and epochs
have an inverse relationship and I'm using that term very lightly and in a
purely descriptive sense). The `low_e` epoch seems to have more balanced rates
although low.

Lets examine a plot to visualize if `low_e` is actually the epoch with most
favorable performance:

```{python}
#| eval: true
#| code-fold: true
#| label: ROC_Curves_for_Epochs_Code
#| code-summary: "ROC Curves for Epochs"


#-- lables-- 
epoch_labels= {"low_e": "Low Rate Epoch", "mid_e": "Mid rate Epoch", "high_e": "High Rate Epoch"}

plt.figure(figsize=(8,6))

for epoch, group in epoch_results.groupby("epoch"):
  false_positive_rate, true_positive_rate, thresholds= roc_curve(group["y_true"], group["y_prob"])
  roc_auc= roc_auc_score(group["y_true"], group["y_prob"])
  plt.plot(false_positive_rate, true_positive_rate,
  label=f"{epoch_labels[epoch]} (AUC={roc_auc:.2f})")

#-- comparison line--
plt.plot([0,1],[0,1],'-', label="Chance")

plt.title("ROC Curves by Epoch", pad=15)
plt.xlabel("")
plt.ylabel("")
plt.legend()
plt.show()
```

The plot shows that the low rate epoch has better performance since its the
furthest away from the line that's random/ "by chance".

The plot below shows model performance as well and whether the model predictions
were over or under. The diagonal line represents the actual outcomes vs model
predictions in a perfect world. We can observe that the model on the `low_e`
(green) epoch is relatively close to the diagonal although it has various
occasions of over or under predicting. The other two lines we can see end before
the `low_e` does. The `high_e` line either does not make predictions above 0.2,
or it follows `mid_e` and is hiding behind it. It may be possible that model
prediction is most favorable in a `low_e` or low interest rate epoch because the
relationship between the economic predictors and customer decisions was more
stable.

```{python}
#| eval: true
#| code-fold: true
#| label: Calibration_Curves_for_Epochs
#| code-summary: "Predictions vs Outcomes"

plt.figure(figsize=(10,10))

for epoch, group in epoch_results.groupby("epoch"):
  prob_true, prob_pred= calibration_curve(group["y_true"], group["y_prob"], n_bins=8)
  plt.plot(prob_pred, prob_true, marker='.', 
  label=f"{epoch_labels[epoch]}")

plt.plot([0,1],[0,1],'--', color= "gray")
plt.title("Calibration Curves by Epoch", pad=15)
plt.xlabel("model prediction")
plt.ylabel("actual outcomes")
plt.legend()
plt.show()
```

::: {.card .border-primary .mb-3 style="padding: 20px"}
#### Lift Curves and Hit Rates:

Your marketing team is planning a marketing campaign where they will call the
top $x$ percent of likely clients based on based on model forecasts. Lift
describes the ratio of the success rate in the top $x$ percent to the success
rate in the entire population and hit rate means the fraction of marketing calls
that are successful. A campaign that targets the top 1% will have a much higher
lift than one that targets the top 50%, and the lift of a campaign that targets
everyone will be 1.

A lift curve is a graph showing the lift on the y-axis and the percent targeted
on the x-axis. Lift curves and hit rates are essential tools used to estimate
the return on investment of a campaign. Estimate the lift on the testing set
corresponding to each epoch by sorting the testing examples in descending order
of predicted probability and then calculating the fraction of successful
conversions in the top $x$ percent and dividing by the total number of
successful conversions in the testing set.\
\
Make a plot of the lift curve using your baseline model for each epoch and
report the lift and hit rate for campaigns that target the top 10% and top 50%
of potential customers.
:::

```{python}
#| eval: true
#| code-fold: true
#| label: Lift_Curves
#| code-summary: "Lift Curves Setup Code"

#-- Result catcher--
lift_results= []

#-- Grouping by Epoch--
for epoch, group in epoch_results.groupby("epoch"):
  group= group.sort_values("y_prob", ascending=False).reset_index(drop=True)
  successfulness= group["y_true"].mean()
  for x in [0.01, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.75, 1.00]:
    n= max(1, int(len(group) * x))
    top_x= group.iloc[:n]
    hit_rate= top_x["y_true"].mean()
    lift= hit_rate / successfulness
    lift_results.append({"epoch": epoch, "campaign_target": x * 100, "hit_rate": hit_rate, "lift": lift})

#-- Convert to dataframe--
results= pd.DataFrame(lift_results)
```

The plot below shows the lift rates overall at 1-100% target. The 1% and 50% are
marked by a circle. We can observe that the epoch performance with the highest
lift in selecting the top 1% of targets is the Mid Rate Epoch. At a 50% target,
the best performing is the Low Rate Epoch. Lift drops dramatically when
targeting more that 20% so at the very least there is benefit to using the model
for target selection than just random calls. Probably the top 1% considering the
lift is over 4.

```{python}
#| eval: true
#| code-fold: true
#| label: Lift_Curve-Plot
#| code-summary: "Lift Curve Plot Code"

plt.figure(figsize=(10,8))

for epoch, group in results.groupby("epoch"):
  plt.plot(group["campaign_target"], group["lift"],
  label=f"{epoch_labels[epoch]}")
#-- marking the 1% and 50%--
  mark= group[group["campaign_target"].isin([1, 50])]
  plt.scatter(mark["campaign_target"], mark["lift"], zorder=3)

#-- Random Baseline--
plt.axhline(1, linestyle="--", label="Chance", color= "gray")

plt.title("Lift Curves by Epoch", pad=15)
plt.xlabel("Percent of Customers Targeted")
plt.ylabel("Lift")
plt.legend()
plt.show()
```

::: {.card .border-primary .mb-3 style="padding: 20px"}
### Extra Credit (5 pts): How Has the Marketing Team Already Been Optimizing?

Understanding the data generating process is vital for modeling. This marketing
dataset is not a random sample of the bank's customers. Marketers may already be
using a model or their own expertise to select which customers to call. This
could lead to selection bias, where segments of the population are not
represented in the dataset. As the marketing campaign progressed, the marketing
team may also have gained knowledge about the most effective practices, which
could explain some of the temporal anomalies. Can you find evidence for this in
any of the variables in the dataset?

Note: there is a trade-off between exploration (getting data to improve the
model accuracy) and exploitation (making calls to optimize the number of term
deposits the bank sells). This trade-off is often referred to as a "multi-armed
bandit" problem, see <https://en.wikipedia.org/wiki/Multi-armed_bandit>.
:::

The existence of the variable `euribor3m` suggests the marketing team might have
already considered optimizing. Euribor is an established reference and is
published daily. This means they calculated a single (probably averaged) rate
and selected 3 months as an economic market. They were aware of the need for
epochs. Also there are several variables providing context about client contacts
including contact type. It seems they were even considering if calling a
landline or cellphone might influence a clients decision by including this.

--------------------------------------------------------------------------------

## Bibliography

Module 4: Classification

<https://georgehagstrom.github.io/DATA622Spring2026/modules/module4.html>

Cumulative Response and Lift Curves- Mitchell R. Wenger

<https://www.youtube.com/watch?v=DTC7BkhNZYk&t=13s>

Multi-Armed Bandit : Data Science Concepts- Ritvikmath

<https://www.youtube.com/watch?v=e3L4VocZnnQ>
